# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6644eca9f9caab002deb844bb8ffe0f429f6c7d83223e83814b9cc115dbc28b9dc27e40975cdcc48b69585e7a48640b8f289f8f30fa440cbacbd3bb35fcc582b

test:
  secret_key_base: 25e18a615018f5fa9608a5bab9311f28d55f59a641fc4821625eaf54362ee91cda0d3ae37781b547920fdf457ef4f2aec84ac36a53fb8b9bf618f08d35406ccf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
